### ISSUE TITLE
[Bug]搜索记录无法删除

### ISSUE THREAD

**Issue by sajiawuwu** [hakadao/bilibili-simple-home#6]
搜索栏中的搜索记录，无法删除

**Comment by flashorsink** [comment]
确实，搜索记录点小叉没办法删除单条记录了，就是小叉无效了。

**Comment by flashorsink** [comment]
试了下开启聚焦选项才会无效的，关闭聚焦选项后是正常的，大概是层级问题？

**Comment by hakadao** [comment]
应该是层级搞错了，我过会看看

**Comment by hakadao** [comment]
有点绝望，怎么搞都是差那么一点
这是原本的写法
之所以怎么做关闭历史操作是因为 #3 

```css
.international-header .nav-search::before {
    content: '';
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0);
    transition: .25s ease-in-out;
    visibility: hidden;
    z-index: -1;
}

.international-header .nav-search:focus-within::before {
    background-color: rgba(0, 0, 0, .5);
    visibility: visible;
    /*[[FOCUS_BLUR]]*/
}

/*原本就是下面这些判断，但失去搜索框焦点时关闭历史记录。但是没有想到点击历史记录时候同时也失去搜索框焦点*/
.international-header .nav-search .bilibili-search-suggest,
.international-header .nav-search .bilibili-search-history{
    display: none;
}

.international-header .nav-search:focus-within .bilibili-search-suggest,
.international-header .nav-search:focus-within .bilibili-search-history{
    display: block;
} 
```

这种效果是实现了删除效果，但每次删除就关闭历史记录
```css
.international-header .nav-search .bilibili-search-suggest,
.international-header .nav-search .bilibili-search-history{
    display: none;
}

.international-header .nav-search .bilibili-search-suggest:active,
.international-header .nav-search .bilibili-search-history:active,
.international-header .nav-search:focus-within .bilibili-search-suggest,
.international-header .nav-search:focus-within .bilibili-search-history{
    display: block;
} 
```
当然还有一个更简单粗暴但方法，就是通过`box-shadow`来实现背景暗化，但这么做模糊效果不能实现，并且对部分机子来说蜜汁卡顿
```css
box-shadow: 0 0 0 2000px rgba(0, 0, 0, .6);
```
